// <auto-generated />
namespace PracaInzynierska.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v_10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v_10));
        
        string IMigrationMetadata.Id
        {
            get { return "201611261247434_v_1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
