//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaInzynierska
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PracaInzynierskaEntities8 : DbContext
    {
        public PracaInzynierskaEntities8()
            : base("name=PracaInzynierskaEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_CarRequests> TB_CarRequests { get; set; }
        public virtual DbSet<TB_Clients> TB_Clients { get; set; }
        public virtual DbSet<TB_ClientsCars> TB_ClientsCars { get; set; }
        public virtual DbSet<TB_ClientsInfo> TB_ClientsInfo { get; set; }
        public virtual DbSet<TB_Logins> TB_Logins { get; set; }
        public virtual DbSet<TB_Messages> TB_Messages { get; set; }
        public virtual DbSet<TB_RepairOrders> TB_RepairOrders { get; set; }
        public virtual DbSet<TB_Roles> TB_Roles { get; set; }
        public virtual DbSet<TB_SalaryReport> TB_SalaryReport { get; set; }
        public virtual DbSet<TB_ServicesCars> TB_ServicesCars { get; set; }
        public virtual DbSet<TB_Users> TB_Users { get; set; }
        public virtual DbSet<TB_Workers> TB_Workers { get; set; }
    }
}
