//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaInzynierska
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ClientsInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ClientsInfo()
        {
            this.TB_ClientsCars = new HashSet<TB_ClientsCars>();
        }
    
        public int ClientInfoId { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public System.DateTime ProductionYear { get; set; }
        public double Capacity { get; set; }
        public string Type { get; set; }
        public string EngineType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ClientsCars> TB_ClientsCars { get; set; }
    }
}
