//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaInzynierska
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ClientsCars
    {
        public int ClientCarId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string StreetName { get; set; }
        public string HomeNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Company { get; set; }
        public Nullable<int> ClientInfoId { get; set; }
    
        public virtual TB_ClientsInfo TB_ClientsInfo { get; set; }
    }
}
