//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaInzynierska
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Logins
    {
        public int LoginId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual TB_Users TB_Users { get; set; }
    }
}
