//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaInzynierska
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Messages
    {
        public int MessageId { get; set; }
        public string Title { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public string MessageContent { get; set; }
    
        public virtual TB_Clients TB_Clients { get; set; }
        public virtual TB_Workers TB_Workers { get; set; }
    }
}
