//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaInzynierska
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SalaryReport
    {
        public int SalaryReportId { get; set; }
        public System.DateTime CountingStartTime { get; set; }
        public System.DateTime CountingEndTime { get; set; }
        public double Salary { get; set; }
        public double Bonus { get; set; }
        public Nullable<int> WorkerId { get; set; }
    
        public virtual TB_Workers TB_Workers { get; set; }
    }
}
