//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaInzynierska
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Users
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Sex { get; set; }
        public string PhoneNumber { get; set; }
        public string NameRole { get; set; }
    
        public virtual TB_Clients TB_Clients { get; set; }
        public virtual TB_Logins TB_Logins { get; set; }
        public virtual TB_Roles TB_Roles { get; set; }
        public virtual TB_Workers TB_Workers { get; set; }
    }
}
