//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaInzynierska
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Workers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Workers()
        {
            this.TB_Messages = new HashSet<TB_Messages>();
            this.TB_RepairOrders = new HashSet<TB_RepairOrders>();
            this.TB_SalaryReport = new HashSet<TB_SalaryReport>();
        }
    
        public int WorkerId { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string StreetName { get; set; }
        public string HouseNumber { get; set; }
        public Nullable<System.DateTime> DateOfEmployment { get; set; }
        public Nullable<System.DateTime> DateOfRelease { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Messages> TB_Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_RepairOrders> TB_RepairOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SalaryReport> TB_SalaryReport { get; set; }
        public virtual TB_Users TB_Users { get; set; }
    }
}
